"""split with enplans

Revision ID: 2ff307da7ca1
Revises: 
Create Date: 2026-09-01 11:36:12.783508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ff307da7ca1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('directions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=400), nullable=True),
    sa.Column('name', sa.String(length=400), nullable=True),
    sa.Column('id_unit', sa.Integer(), nullable=True),
    sa.Column('DateStart', sa.DateTime(), nullable=True),
    sa.Column('DateEnd', sa.DateTime(), nullable=True),
    sa.Column('is_econom', sa.Boolean(), nullable=True),
    sa.Column('is_increase', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_unit'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_unit', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=400), nullable=True),
    sa.Column('name', sa.String(length=400), nullable=True),
    sa.Column('CoeffToTut', sa.Numeric(scale=3), nullable=True),
    sa.Column('is_local', sa.Boolean(), nullable=True),
    sa.Column('is_renewable', sa.Boolean(), nullable=True),
    sa.Column('IsMandatory', sa.Boolean(), nullable=True),
    sa.Column('Group', sa.Float(), nullable=True),
    sa.Column('RowN', sa.Integer(), nullable=True),
    sa.Column('DateStart', sa.DateTime(), nullable=True),
    sa.Column('DateEnd', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_unit'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=140), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('begin_time', sa.DateTime(), nullable=False),
    sa.Column('change_time', sa.DateTime(), nullable=False),
    sa.Column('sent_time', sa.DateTime(), nullable=True),
    sa.Column('audit_time', sa.DateTime(), nullable=True),
    sa.Column('energy_saving', sa.Numeric(scale=1), nullable=True),
    sa.Column('share_fuel', sa.Numeric(scale=1), nullable=True),
    sa.Column('saving_fuel', sa.Numeric(scale=1), nullable=True),
    sa.Column('share_energy', sa.Numeric(scale=1), nullable=True),
    sa.Column('afch', sa.Boolean(), nullable=True),
    sa.Column('usd_rate', sa.Numeric(scale=4), nullable=True),
    sa.Column('cost_per_toe_usd', sa.Numeric(scale=2), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('is_control', sa.Boolean(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('is_error', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('plan_type', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_token'), ['token'], unique=True)

    op.create_table('stat_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'type', 'year', name='uq_stat_plan_org_type_year')
    )
    op.create_table('user_app_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('app', sa.String(length=32), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'app', name='uq_user_app_activity')
    )
    op.create_table('Plan_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('begin_time', sa.DateTime(), nullable=True),
    sa.Column('luck', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('is_user', sa.Boolean(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_direction', sa.Integer(), nullable=False),
    sa.Column('id_plan', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=4000), nullable=False),
    sa.Column('display_code', sa.String(length=400), nullable=True),
    sa.Column('Volume', sa.Integer(), nullable=True),
    sa.Column('EffTut', sa.Numeric(scale=2), nullable=True),
    sa.Column('EffRub', sa.Integer(), nullable=True),
    sa.Column('ExpectedQuarter', sa.String(), nullable=True),
    sa.Column('EffCurrYear', sa.Numeric(scale=2), nullable=True),
    sa.Column('Payback', sa.Numeric(scale=1), nullable=True),
    sa.Column('ObchVolumeFin', sa.Integer(), nullable=True),
    sa.Column('VolumeFinCurrentYear', sa.Integer(), nullable=True),
    sa.Column('BudgetState', sa.Integer(), nullable=True),
    sa.Column('BudgetRep', sa.Integer(), nullable=True),
    sa.Column('BudgetLoc', sa.Integer(), nullable=True),
    sa.Column('BudgetOther', sa.Integer(), nullable=True),
    sa.Column('MoneyOwn', sa.Integer(), nullable=True),
    sa.Column('MoneyLoan', sa.Integer(), nullable=True),
    sa.Column('MoneyOther', sa.Integer(), nullable=True),
    sa.Column('is_local', sa.Boolean(), nullable=True),
    sa.Column('is_corrected', sa.Boolean(), nullable=True),
    sa.Column('is_econom', sa.Boolean(), nullable=True),
    sa.Column('is_increase', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_direction'], ['directions.id'], ),
    sa.ForeignKeyConstraint(['id_plan'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicators_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_indicator', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('id_plan', sa.Integer(), nullable=False),
    sa.Column('QYearBeforePrev', sa.Numeric(scale=2), nullable=True),
    sa.Column('QYearPrev', sa.Numeric(scale=2), nullable=True),
    sa.Column('QYearCurrent', sa.Numeric(scale=2), nullable=True),
    sa.Column('is_local', sa.Boolean(), nullable=True),
    sa.Column('is_renewable', sa.Boolean(), nullable=True),
    sa.Column('coeff_before_prev', sa.Numeric(scale=3), nullable=True),
    sa.Column('coeff_prev', sa.Numeric(scale=3), nullable=True),
    sa.Column('coeff_current', sa.Numeric(scale=3), nullable=True),
    sa.ForeignKeyConstraint(['id_indicator'], ['indicators.id'], ),
    sa.ForeignKeyConstraint(['id_plan'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_approval_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=20), nullable=False),
    sa.Column('is_viewed', sa.Boolean(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_column_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stat_plan_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat_plan_id', sa.Integer(), nullable=False),
    sa.Column('row_code', sa.String(length=20), nullable=False),
    sa.Column('row_name', sa.String(length=500), nullable=True),
    sa.Column('column_code', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Numeric(scale=4), nullable=True),
    sa.ForeignKeyConstraint(['stat_plan_id'], ['stat_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_plan_id', 'row_code', 'column_code', name='uq_stat_value_cell')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_erespondentn', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_enplans', sa.Boolean(), nullable=True))
        batch_op.alter_column('img_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=True))
        batch_op.add_column(sa.Column('is_auditor', sa.Boolean(), server_default='false', nullable=True))
        batch_op.add_column(sa.Column('is_approver', sa.Boolean(), server_default='false', nullable=True))
        batch_op.add_column(sa.Column('is_reader', sa.Boolean(), server_default='false', nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('patronymic_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('post', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('begin_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reset_password_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_password_expires', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_active', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('reset_password_expires')
        batch_op.drop_column('reset_password_token')
        batch_op.drop_column('begin_time')
        batch_op.drop_column('post')
        batch_op.drop_column('patronymic_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')
        batch_op.drop_column('is_reader')
        batch_op.drop_column('is_approver')
        batch_op.drop_column('is_auditor')
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('img_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('is_enplans')
        batch_op.drop_column('is_erespondentn')

    op.drop_table('stat_plan_values')
    op.drop_table('plan_column_configs')
    op.drop_table('plan_approval_paths')
    op.drop_table('indicators_usage')
    op.drop_table('events')
    op.drop_table('chat_messages')
    op.drop_table('Plan_tickets')
    op.drop_table('user_app_activity')
    op.drop_table('stat_plans')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_token'))

    op.drop_table('plans')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    op.drop_table('chats')
    op.drop_table('indicators')
    op.drop_table('directions')
    op.drop_table('units')
    # ### end Alembic commands ###
